// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250511035113_addNullablePropertiesForKhachHang")]
    partial class addNullablePropertiesForKhachHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.ChiTietPhieuSuaChua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PhieuSuaChuaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<Guid>("TienCongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VatTuPhuTungId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("chiTietPhieuSuaChuas");
                });

            modelBuilder.Entity("WebAPI.Models.ChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenManHinhDuocLoad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("chucNangs");
                });

            modelBuilder.Entity("WebAPI.Models.HieuXe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenHieuXe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hieuXes");
                });

            modelBuilder.Entity("WebAPI.Models.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaCoTaiKhoan")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NhomNguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TienNo")
                        .HasColumnType("float");

                    b.Property<int?>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("WebAPI.Models.NhomNguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nhomNguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3be2914d-cfee-4ba5-9d89-2b53ad3e4954"),
                            TenNhom = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c119a7ee-d76c-42f4-9002-e0229c49618e"),
                            TenNhom = "User"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.PhanQuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChucNangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NhomNguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("phanQuyens");
                });

            modelBuilder.Entity("WebAPI.Models.PhieuSuaChua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgaySuaChua")
                        .HasColumnType("datetime2");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<Guid>("XeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("phieuSuaChuas");
                });

            modelBuilder.Entity("WebAPI.Models.PhieuThuTien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayThuTien")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoTienThu")
                        .HasColumnType("float");

                    b.Property<Guid>("XeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("phieuThuTiens");
                });

            modelBuilder.Entity("WebAPI.Models.PhieuTiepNhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("XeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("phieuTiepNhans");
                });

            modelBuilder.Entity("WebAPI.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NhomNguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("taiKhoans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7de66f4-2cc8-446b-9e43-968fd9b4921d"),
                            MatKhau = "admin123",
                            NhomNguoiDungId = new Guid("3be2914d-cfee-4ba5-9d89-2b53ad3e4954"),
                            TenDangNhap = "admin"
                        },
                        new
                        {
                            Id = new Guid("4c3e80ca-2aa6-4046-ab92-a83ac9d61fc3"),
                            MatKhau = "user123",
                            NhomNguoiDungId = new Guid("c119a7ee-d76c-42f4-9002-e0229c49618e"),
                            TenDangNhap = "user"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.ThamSo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GiaTri")
                        .HasColumnType("int");

                    b.Property<string>("TenThamSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("thamSos");
                });

            modelBuilder.Entity("WebAPI.Models.TienCong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGiaLoaiTienCong")
                        .HasColumnType("float");

                    b.Property<string>("TenLoaiTienCong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tienCongs");
                });

            modelBuilder.Entity("WebAPI.Models.VatTuPhuTung", b =>
                {
                    b.Property<Guid>("VatTuPhuTungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGiaBanLoaiVatTuPhuTung")
                        .HasColumnType("float");

                    b.Property<double>("DonGiaNhapLoaiVatTuPhuTung")
                        .HasColumnType("float");

                    b.Property<string>("TenLoaiVatTuPhuTung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VatTuPhuTungId");

                    b.ToTable("vatTuPhuTungs");
                });

            modelBuilder.Entity("WebAPI.Models.Xe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HieuXeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("KhaDung")
                        .HasColumnType("bit");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TienNo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("xes");
                });
#pragma warning restore 612, 618
        }
    }
}
