// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250522091110_add MoTa for ThamSo indeed")]
    partial class addMoTaforThamSoindeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.BaoCaoDoanhThuThang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<double>("TongDoanhThu")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("baoCaoDoanhThuThangs");
                });

            modelBuilder.Entity("WebAPI.Models.BaoCaoTon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("baoCaoTons");
                });

            modelBuilder.Entity("WebAPI.Models.ChiTietBaoCaoDoanhThuThang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaoCaoDoanhThuThangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HieuXeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuotSua")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<float>("TiLe")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("chiTietBaoCaoDoanhThuThangs");
                });

            modelBuilder.Entity("WebAPI.Models.ChiTietBaoCaoTon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaoCaoTonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PhatSinh")
                        .HasColumnType("int");

                    b.Property<int>("TonCuoi")
                        .HasColumnType("int");

                    b.Property<int>("TonDau")
                        .HasColumnType("int");

                    b.Property<Guid>("VatTuPhuTungId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("chiTietBaoCaoTons");
                });

            modelBuilder.Entity("WebAPI.Models.ChiTietPhieuNhapVatTu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("PhieuNhapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<Guid>("VatTuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("chiTietPhieuNhapVatTus");
                });

            modelBuilder.Entity("WebAPI.Models.ChiTietPhieuSuaChua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NoiDungSuaChuaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhieuSuaChuaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<Guid>("TienCongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("chiTietPhieuSuaChuas");
                });

            modelBuilder.Entity("WebAPI.Models.ChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenManHinhDuocLoad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("chucNangs");
                });

            modelBuilder.Entity("WebAPI.Models.HieuXe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenHieuXe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hieuXes");
                });

            modelBuilder.Entity("WebAPI.Models.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TienNo")
                        .HasColumnType("float");

                    b.Property<int?>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("WebAPI.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("WebAPI.Models.NhomNguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nhomNguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40a4a728-66b5-493f-8362-fd0ad9fa7e70"),
                            TenNhom = "Admin"
                        },
                        new
                        {
                            Id = new Guid("ba82589d-6b3c-4444-8558-622da49e62a9"),
                            TenNhom = "User"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.NoiDungSuaChua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenNoiDungSuaChua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("noiDungSuaChuas");
                });

            modelBuilder.Entity("WebAPI.Models.PhanQuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChucNangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NhomNguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("phanQuyens");
                });

            modelBuilder.Entity("WebAPI.Models.PhieuNhapVatTu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("phieuNhapVatTus");
                });

            modelBuilder.Entity("WebAPI.Models.PhieuSuaChua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgaySuaChua")
                        .HasColumnType("datetime2");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<Guid>("XeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("phieuSuaChuas");
                });

            modelBuilder.Entity("WebAPI.Models.PhieuThuTien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayThuTien")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoTienThu")
                        .HasColumnType("float");

                    b.Property<Guid>("XeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("phieuThuTiens");
                });

            modelBuilder.Entity("WebAPI.Models.PhieuTiepNhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaHoanThanhBaoTri")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("XeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("phieuTiepNhans");
                });

            modelBuilder.Entity("WebAPI.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NhomNguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("taiKhoans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9cf6216e-0145-4506-9362-4fc9e8c2d4d6"),
                            MatKhau = "admin123",
                            NhomNguoiDungId = new Guid("40a4a728-66b5-493f-8362-fd0ad9fa7e70"),
                            TenDangNhap = "admin"
                        },
                        new
                        {
                            Id = new Guid("086289eb-370d-49e9-9809-38f298f8357d"),
                            MatKhau = "user123",
                            NhomNguoiDungId = new Guid("ba82589d-6b3c-4444-8558-622da49e62a9"),
                            TenDangNhap = "user"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.ThamSo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GiaTri")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThamSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("thamSos");
                });

            modelBuilder.Entity("WebAPI.Models.TienCong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGiaLoaiTienCong")
                        .HasColumnType("float");

                    b.Property<Guid>("NoiDungSuaChuaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenLoaiTienCong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tienCongs");
                });

            modelBuilder.Entity("WebAPI.Models.VTPTChiTietPhieuSuaChua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChiTietPhieuSuaChuaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<Guid>("VatTuPhuTungId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("vtptChiTietPhieuSuaChuas");
                });

            modelBuilder.Entity("WebAPI.Models.VatTuPhuTung", b =>
                {
                    b.Property<Guid>("VatTuPhuTungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGiaBanLoaiVatTuPhuTung")
                        .HasColumnType("float");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiVatTuPhuTung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VatTuPhuTungId");

                    b.ToTable("vatTuPhuTungs");
                });

            modelBuilder.Entity("WebAPI.Models.Xe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HieuXeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("KhaDung")
                        .HasColumnType("bit");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TienNo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("xes");
                });
#pragma warning restore 612, 618
        }
    }
}
